### ISSUE TITLE
Can't run the sample. What am I missing?

### ISSUE THREAD

**Issue by gabriel-wainmann** [muelea/shapy#22]
Hi

Ubuntu 22.04, GPU, Python10.

After following the installation instructions, I get this:

`(venv) shmendrik@gabriel-Raider:~/Documents/BodyBuilder/shapy/regressor$ python demo.py --save-vis true --save-params true --save-mesh true --split test --datasets openpose --output-folder ../samples/shapy_fit/ --exp-cfg configs/b2a_expose_hrnet_demo.yaml --exp-opts output_folder=../data/trained_models/shapy/SHAPY_A part_key=pose datasets.pose.openpose.data_folder=../samples datasets.pose.openpose.img_folder=images  datasets.pose.openpose.keyp_folder=openpose datasets.batch_size=1 datasets.pose_shape_ratio=1.0
Traceback (most recent call last):
  File "/home/shmendrik/Documents/BodyBuilder/shapy/regressor/demo.py", line 23, in <module>
    from human_shape.config.defaults import conf as default_conf
  File "/home/shmendrik/Documents/BodyBuilder/shapy/regressor/human_shape/config/__init__.py", line 2, in <module>
    from .cmd_parser import parse_args
  File "/home/shmendrik/Documents/BodyBuilder/shapy/regressor/human_shape/config/cmd_parser.py", line 9, in <module>
    from .defaults import conf as default_conf
  File "/home/shmendrik/Documents/BodyBuilder/shapy/regressor/human_shape/config/defaults.py", line 6, in <module>
    from .network_defaults import conf as network_cfg, Network
  File "/home/shmendrik/Documents/BodyBuilder/shapy/regressor/human_shape/config/network_defaults.py", line 268, in <module>
    conf = OmegaConf.structured(Network)
  File "/home/shmendrik/Documents/BodyBuilder/shapy/venv/lib/python3.10/site-packages/omegaconf/omegaconf.py", line 125, in structured
    return OmegaConf.create(obj, parent, flags)
  File "/home/shmendrik/Documents/BodyBuilder/shapy/venv/lib/python3.10/site-packages/omegaconf/omegaconf.py", line 178, in create
    return OmegaConf._create_impl(
  File "/home/shmendrik/Documents/BodyBuilder/shapy/venv/lib/python3.10/site-packages/omegaconf/omegaconf.py", line 900, in _create_impl
    format_and_raise(node=None, key=None, value=None, msg=str(e), cause=e)
  File "/home/shmendrik/Documents/BodyBuilder/shapy/venv/lib/python3.10/site-packages/omegaconf/_utils.py", line 819, in format_and_raise
    _raise(ex, cause)
  File "/home/shmendrik/Documents/BodyBuilder/shapy/venv/lib/python3.10/site-packages/omegaconf/_utils.py", line 797, in _raise
    raise ex.with_traceback(sys.exc_info()[2])  # set env var OC_CAUSE=1 for full trace
  File "/home/shmendrik/Documents/BodyBuilder/shapy/venv/lib/python3.10/site-packages/omegaconf/omegaconf.py", line 861, in _create_impl
    return DictConfig(
  File "/home/shmendrik/Documents/BodyBuilder/shapy/venv/lib/python3.10/site-packages/omegaconf/dictconfig.py", line 111, in __init__
    format_and_raise(node=None, key=key, value=None, cause=ex, msg=str(ex))
  File "/home/shmendrik/Documents/BodyBuilder/shapy/venv/lib/python3.10/site-packages/omegaconf/_utils.py", line 819, in format_and_raise
    _raise(ex, cause)
  File "/home/shmendrik/Documents/BodyBuilder/shapy/venv/lib/python3.10/site-packages/omegaconf/_utils.py", line 797, in _raise
    raise ex.with_traceback(sys.exc_info()[2])  # set env var OC_CAUSE=1 for full trace
  File "/home/shmendrik/Documents/BodyBuilder/shapy/venv/lib/python3.10/site-packages/omegaconf/dictconfig.py", line 94, in __init__
    self._set_value(content, flags=flags)
  File "/home/shmendrik/Documents/BodyBuilder/shapy/venv/lib/python3.10/site-packages/omegaconf/dictconfig.py", line 647, in _set_value
    raise e
  File "/home/shmendrik/Documents/BodyBuilder/shapy/venv/lib/python3.10/site-packages/omegaconf/dictconfig.py", line 644, in _set_value
    self._set_value_impl(value, flags)
  File "/home/shmendrik/Documents/BodyBuilder/shapy/venv/lib/python3.10/site-packages/omegaconf/dictconfig.py", line 674, in _set_value_impl
    data = get_structured_config_data(value, allow_objects=ao)
  File "/home/shmendrik/Documents/BodyBuilder/shapy/venv/lib/python3.10/site-packages/omegaconf/_utils.py", line 495, in get_structured_config_data
    return get_dataclass_data(obj, allow_objects=allow_objects)
  File "/home/shmendrik/Documents/BodyBuilder/shapy/venv/lib/python3.10/site-packages/omegaconf/_utils.py", line 421, in get_dataclass_data
    format_and_raise(
  File "/home/shmendrik/Documents/BodyBuilder/shapy/venv/lib/python3.10/site-packages/omegaconf/_utils.py", line 819, in format_and_raise
    _raise(ex, cause)
  File "/home/shmendrik/Documents/BodyBuilder/shapy/venv/lib/python3.10/site-packages/omegaconf/_utils.py", line 797, in _raise
    raise ex.with_traceback(sys.exc_info()[2])  # set env var OC_CAUSE=1 for full trace
  File "/home/shmendrik/Documents/BodyBuilder/shapy/venv/lib/python3.10/site-packages/omegaconf/_utils.py", line 413, in get_dataclass_data
    d[name] = _maybe_wrap(
  File "/home/shmendrik/Documents/BodyBuilder/shapy/venv/lib/python3.10/site-packages/omegaconf/omegaconf.py", line 1105, in _maybe_wrap
    return _node_wrap(
  File "/home/shmendrik/Documents/BodyBuilder/shapy/venv/lib/python3.10/site-packages/omegaconf/omegaconf.py", line 1027, in _node_wrap
    node = DictConfig(
  File "/home/shmendrik/Documents/BodyBuilder/shapy/venv/lib/python3.10/site-packages/omegaconf/dictconfig.py", line 111, in __init__
    format_and_raise(node=None, key=key, value=None, cause=ex, msg=str(ex))
  File "/home/shmendrik/Documents/BodyBuilder/shapy/venv/lib/python3.10/site-packages/omegaconf/_utils.py", line 819, in format_and_raise
    _raise(ex, cause)
  File "/home/shmendrik/Documents/BodyBuilder/shapy/venv/lib/python3.10/site-packages/omegaconf/_utils.py", line 797, in _raise
    raise ex.with_traceback(sys.exc_info()[2])  # set env var OC_CAUSE=1 for full trace
  File "/home/shmendrik/Documents/BodyBuilder/shapy/venv/lib/python3.10/site-packages/omegaconf/dictconfig.py", line 94, in __init__
    self._set_value(content, flags=flags)
  File "/home/shmendrik/Documents/BodyBuilder/shapy/venv/lib/python3.10/site-packages/omegaconf/dictconfig.py", line 647, in _set_value
    raise e
  File "/home/shmendrik/Documents/BodyBuilder/shapy/venv/lib/python3.10/site-packages/omegaconf/dictconfig.py", line 644, in _set_value
    self._set_value_impl(value, flags)
  File "/home/shmendrik/Documents/BodyBuilder/shapy/venv/lib/python3.10/site-packages/omegaconf/dictconfig.py", line 674, in _set_value_impl
    data = get_structured_config_data(value, allow_objects=ao)
  File "/home/shmendrik/Documents/BodyBuilder/shapy/venv/lib/python3.10/site-packages/omegaconf/_utils.py", line 495, in get_structured_config_data
    return get_dataclass_data(obj, allow_objects=allow_objects)
  File "/home/shmendrik/Documents/BodyBuilder/shapy/venv/lib/python3.10/site-packages/omegaconf/_utils.py", line 421, in get_dataclass_data
    format_and_raise(
  File "/home/shmendrik/Documents/BodyBuilder/shapy/venv/lib/python3.10/site-packages/omegaconf/_utils.py", line 819, in format_and_raise
    _raise(ex, cause)
  File "/home/shmendrik/Documents/BodyBuilder/shapy/venv/lib/python3.10/site-packages/omegaconf/_utils.py", line 797, in _raise
    raise ex.with_traceback(sys.exc_info()[2])  # set env var OC_CAUSE=1 for full trace
  File "/home/shmendrik/Documents/BodyBuilder/shapy/venv/lib/python3.10/site-packages/omegaconf/_utils.py", line 413, in get_dataclass_data
    d[name] = _maybe_wrap(
  File "/home/shmendrik/Documents/BodyBuilder/shapy/venv/lib/python3.10/site-packages/omegaconf/omegaconf.py", line 1105, in _maybe_wrap
    return _node_wrap(
  File "/home/shmendrik/Documents/BodyBuilder/shapy/venv/lib/python3.10/site-packages/omegaconf/omegaconf.py", line 1017, in _node_wrap
    node = ListConfig(
  File "/home/shmendrik/Documents/BodyBuilder/shapy/venv/lib/python3.10/site-packages/omegaconf/listconfig.py", line 82, in __init__
    format_and_raise(node=None, key=key, value=None, cause=ex, msg=str(ex))
  File "/home/shmendrik/Documents/BodyBuilder/shapy/venv/lib/python3.10/site-packages/omegaconf/_utils.py", line 819, in format_and_raise
    _raise(ex, cause)
  File "/home/shmendrik/Documents/BodyBuilder/shapy/venv/lib/python3.10/site-packages/omegaconf/_utils.py", line 797, in _raise
    raise ex.with_traceback(sys.exc_info()[2])  # set env var OC_CAUSE=1 for full trace
  File "/home/shmendrik/Documents/BodyBuilder/shapy/venv/lib/python3.10/site-packages/omegaconf/listconfig.py", line 80, in __init__
    self._set_value(value=content, flags=flags)
  File "/home/shmendrik/Documents/BodyBuilder/shapy/venv/lib/python3.10/site-packages/omegaconf/listconfig.py", line 618, in _set_value
    raise e
  File "/home/shmendrik/Documents/BodyBuilder/shapy/venv/lib/python3.10/site-packages/omegaconf/listconfig.py", line 614, in _set_value
    self._set_value_impl(value, flags)
  File "/home/shmendrik/Documents/BodyBuilder/shapy/venv/lib/python3.10/site-packages/omegaconf/listconfig.py", line 659, in _set_value_impl
    self.append(item)
  File "/home/shmendrik/Documents/BodyBuilder/shapy/venv/lib/python3.10/site-packages/omegaconf/listconfig.py", line 301, in append
    self._format_and_raise(key=index, value=item, cause=e)
  File "/home/shmendrik/Documents/BodyBuilder/shapy/venv/lib/python3.10/site-packages/omegaconf/base.py", line 231, in _format_and_raise
    format_and_raise(
  File "/home/shmendrik/Documents/BodyBuilder/shapy/venv/lib/python3.10/site-packages/omegaconf/_utils.py", line 819, in format_and_raise
    _raise(ex, cause)
  File "/home/shmendrik/Documents/BodyBuilder/shapy/venv/lib/python3.10/site-packages/omegaconf/_utils.py", line 797, in _raise
    raise ex.with_traceback(sys.exc_info()[2])  # set env var OC_CAUSE=1 for full trace
  File "/home/shmendrik/Documents/BodyBuilder/shapy/venv/lib/python3.10/site-packages/omegaconf/listconfig.py", line 298, in append
    self._set_item_impl(index, item)
  File "/home/shmendrik/Documents/BodyBuilder/shapy/venv/lib/python3.10/site-packages/omegaconf/basecontainer.py", line 620, in _set_item_impl
    self._wrap_value_and_set(key, value, target_type_hint)
  File "/home/shmendrik/Documents/BodyBuilder/shapy/venv/lib/python3.10/site-packages/omegaconf/basecontainer.py", line 636, in _wrap_value_and_set
    self._format_and_raise(key=key, value=val, cause=e)
  File "/home/shmendrik/Documents/BodyBuilder/shapy/venv/lib/python3.10/site-packages/omegaconf/base.py", line 231, in _format_and_raise
    format_and_raise(
  File "/home/shmendrik/Documents/BodyBuilder/shapy/venv/lib/python3.10/site-packages/omegaconf/_utils.py", line 899, in format_and_raise
    _raise(ex, cause)
  File "/home/shmendrik/Documents/BodyBuilder/shapy/venv/lib/python3.10/site-packages/omegaconf/_utils.py", line 797, in _raise
    raise ex.with_traceback(sys.exc_info()[2])  # set env var OC_CAUSE=1 for full trace
  File "/home/shmendrik/Documents/BodyBuilder/shapy/venv/lib/python3.10/site-packages/omegaconf/basecontainer.py", line 628, in _wrap_value_and_set
    wrapped = _maybe_wrap(
  File "/home/shmendrik/Documents/BodyBuilder/shapy/venv/lib/python3.10/site-packages/omegaconf/omegaconf.py", line 1105, in _maybe_wrap
    return _node_wrap(
  File "/home/shmendrik/Documents/BodyBuilder/shapy/venv/lib/python3.10/site-packages/omegaconf/omegaconf.py", line 1061, in _node_wrap
    node = StringNode(value=value, key=key, parent=parent, is_optional=is_optional)
  File "/home/shmendrik/Documents/BodyBuilder/shapy/venv/lib/python3.10/site-packages/omegaconf/nodes.py", line 174, in __init__
    super().__init__(
  File "/home/shmendrik/Documents/BodyBuilder/shapy/venv/lib/python3.10/site-packages/omegaconf/nodes.py", line 29, in __init__
    self._set_value(value)  # lgtm [py/init-calls-subclass]
  File "/home/shmendrik/Documents/BodyBuilder/shapy/venv/lib/python3.10/site-packages/omegaconf/nodes.py", line 46, in _set_value
    self._val = self.validate_and_convert(value)
  File "/home/shmendrik/Documents/BodyBuilder/shapy/venv/lib/python3.10/site-packages/omegaconf/nodes.py", line 76, in validate_and_convert
    return self._validate_and_convert_impl(value)
  File "/home/shmendrik/Documents/BodyBuilder/shapy/venv/lib/python3.10/site-packages/omegaconf/nodes.py", line 194, in _validate_and_convert_impl
    raise ValidationError("Cannot convert '$VALUE_TYPE' to string: '$VALUE'")
omegaconf.errors.ValidationError: Cannot convert 'tuple' to string: '('betas', 'global_rot', 'body_pose', 'camera')'
    full_key: groups[0]
    reference_type=Tuple[str]
    object_type=list
`

**Comment by krystofjo** [comment]
I am using the one suggested in README.md:

`@ubuntu:~/shapy/regressor$ python demo.py --save-vis true --save-params true --save-mesh true --split test --datasets openpose --output-folder ../samples/shapy_fit/ --exp-cfg configs/b2a_expose_hrnet_demo.yaml --exp-opts output_folder=../data/trained_models/shapy/SHAPY_A part_key=pose datasets.pose.openpose.data_folder=../samples datasets.pose.openpose.img_folder=images  datasets.pose.openpose.keyp_folder=openpose datasets.batch_size=1 datasets.pose_shape_ratio=1.0`

I have doublechecked everything and I am no longer getting the mentioned error after this command.
But I get an ImportError:
`ImportError: cannot import name 'BodyMeasurements' from 'body_measurements' (unknown location)`

I have looked in measurements.py in body_measurements package and I can see no such thing as BodyMeasurements.
Do you have an idea where could be a problem?
Thanks a lot
