### ISSUE TITLE
Import error/issue

### ISSUE THREAD

**Issue by rishitech007** [muelea/shapy#29]
Hi, 
I am encountering this error 
```
from attributes import *
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jupyter/shapy/attributes/attributes/__init__.py", line 1, in <module>
    from .attributes_betas.a2b import A2B, A2BProbabilistic
  File "/home/jupyter/shapy/attributes/attributes/attributes_betas/a2b.py", line 25, in <module>
    from body_measurements import BodyMeasurements
ImportError: cannot import name 'BodyMeasurements' from 'body_measurements' (unknown location)
```

I did a pip install of body_measurements but that does not seem to have resolved the issue. Can you please help with this?

**Comment by zoasif-coder** [comment]
Hey, I am having the same issue. Did you manage to fix this issue?

**Comment by Rut-B** [comment]
run this:
cp /content/shapy/attributes/attributes/* /usr/local/lib/python3.10/dist-packages/attributes/ -r
